[2020-04-08T08:39:34.906] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T08:44:54.962] [ERROR] app - Request without token
[2020-04-08T08:44:54.964] [ERROR] app - 没有访问权限
[2020-04-08T09:08:15.242] [ERROR] app - Request without token
[2020-04-08T09:08:15.243] [ERROR] app - 没有访问权限
[2020-04-08T09:08:52.430] [ERROR] app - Request without token
[2020-04-08T09:08:52.431] [ERROR] app - 没有访问权限
[2020-04-08T09:10:50.415] [ERROR] app - Request without token
[2020-04-08T09:10:50.416] [ERROR] app - 没有访问权限
[2020-04-08T09:11:13.794] [ERROR] app - Request without token
[2020-04-08T09:11:13.795] [ERROR] app - 没有访问权限
[2020-04-08T09:33:31.653] [ERROR] app - Request without token
[2020-04-08T09:33:31.655] [ERROR] app - 没有访问权限
[2020-04-08T09:34:30.410] [ERROR] app - Request without token
[2020-04-08T09:34:30.411] [ERROR] app - 没有访问权限
[2020-04-08T09:45:09.287] [ERROR] app - Request without token
[2020-04-08T09:45:09.290] [ERROR] app - 没有访问权限
[2020-04-08T09:45:54.879] [ERROR] app - Request without token
[2020-04-08T09:45:54.880] [ERROR] app - 没有访问权限
[2020-04-08T09:47:15.373] [ERROR] app - Request without token
[2020-04-08T09:47:15.374] [ERROR] app - 没有访问权限
[2020-04-08T09:49:00.483] [ERROR] app - Request without token
[2020-04-08T09:49:00.485] [ERROR] app - 没有访问权限
[2020-04-08T13:36:39.098] [ERROR] app - 401
[2020-04-08T13:36:39.101] [ERROR] app - 401
[2020-04-08T13:36:39.104] [ERROR] app - 401
[2020-04-08T15:20:42.362] [ERROR] app - Request without token
[2020-04-08T15:20:42.363] [ERROR] app - 没有访问权限
[2020-04-08T15:20:42.419] [ERROR] app - Request without token
[2020-04-08T15:20:42.421] [ERROR] app - 没有访问权限
[2020-04-08T15:21:06.499] [ERROR] app - Request without token
[2020-04-08T15:21:06.499] [ERROR] app - 没有访问权限
[2020-04-08T15:21:23.730] [ERROR] app - Request without token
[2020-04-08T15:21:23.732] [ERROR] app - 没有访问权限
[2020-04-08T15:23:54.542] [ERROR] app - Request without token
[2020-04-08T15:23:54.543] [ERROR] app - 没有访问权限
[2020-04-08T15:25:51.614] [ERROR] app - Request without token
[2020-04-08T15:25:51.615] [ERROR] app - 没有访问权限
[2020-04-08T15:25:54.876] [ERROR] app - Request without token
[2020-04-08T15:25:54.894] [ERROR] app - 没有访问权限
[2020-04-08T16:09:04.124] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:22:00.956] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:23:29.361] [ERROR] app - Request without token
[2020-04-08T16:23:29.363] [ERROR] app - 没有访问权限
[2020-04-08T16:23:32.977] [ERROR] app - ReferenceError: moment is not defined
    at Object.AddRelated (D:\able_project\CloudServer\restful\v0\orders.js:21:21)
    at RestfulAPIMethods.(anonymous function) (D:\able_project\CloudServer\routes\restful.js:32:60)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (D:\able_project\CloudServer\routes\restful.js:97:19)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-compose\index.js:42:32)
    at module.exports (D:\able_project\CloudServer\middlewares\auth.js:54:9)
[2020-04-08T16:23:59.696] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:24:06.177] [ERROR] app - TypeError: util.CreateId is not a function
    at Object.AddRelated (D:\able_project\CloudServer\restful\v0\orders.js:27:26)
    at RestfulAPIMethods.(anonymous function) (D:\able_project\CloudServer\routes\restful.js:32:60)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (D:\able_project\CloudServer\routes\restful.js:97:19)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-compose\index.js:42:32)
    at module.exports (D:\able_project\CloudServer\middlewares\auth.js:54:9)
[2020-04-08T16:24:27.595] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:24:32.518] [ERROR] app - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`content`, `id`, `inputTime`, `inputor`, `order_id`) values ('5123', 'CMT000000' at line 1
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'(`content`, `id`, `inputTime`, `inputor`, `order_id`) values (\'5123\', \'CMT000000\' at line 1',
  sqlState: '42000',
  index: 0,
  sql:
   'insert into  (`content`, `id`, `inputTime`, `inputor`, `order_id`) values (\'5123\', \'CMT00000000000V8\', \'2020-04-08T16:24:32+08:00\', \'UID00000001\', \'order000000000V9\')' }
[2020-04-08T16:26:08.167] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:27:28.231] [ERROR] app - Request without token
[2020-04-08T16:27:28.248] [ERROR] app - 没有访问权限
[2020-04-08T16:30:55.169] [ERROR] app - Request without token
[2020-04-08T16:30:55.171] [ERROR] app - 没有访问权限
[2020-04-08T16:31:47.561] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T16:32:36.842] [ERROR] app - Request without token
[2020-04-08T16:32:36.844] [ERROR] app - 没有访问权限
[2020-04-08T16:32:36.896] [INFO] app - API_METHOD_UNDEFINED:object=orders,method=Related
[2020-04-08T16:44:38.506] [ERROR] app - Request without token
[2020-04-08T16:44:38.508] [ERROR] app - 没有访问权限
[2020-04-08T16:44:38.587] [INFO] app - API_METHOD_UNDEFINED:object=orders,method=Related
[2020-04-08T16:45:17.632] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-08T17:08:08.560] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'order000000000V9' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'order000000000V9\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `reply` (`id`, `inputTime`, `inputor`, `order000000000V9`, `order_id`) values (\'CMT00000000000VD\', \'2020-04-08T17:08:08+08:00\', \'UID00000001\', \'\', \'undefined\')' }
