[2020-04-17T10:34:23.638] [ERROR] app - 401
[2020-04-17T10:34:39.266] [INFO] app - INCORRECT_PASSWORD:
[2020-04-17T10:34:39.267] [ERROR] app - 密码错误
[2020-04-17T10:37:30.010] [ERROR] app - Request without token
[2020-04-17T10:37:30.011] [ERROR] app - 没有访问权限
[2020-04-17T13:43:08.941] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T13:44:23.638] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T13:44:37.602] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T13:44:42.223] [ERROR] app - ReferenceError: knex is not defined
    at Object.Patch (D:\able_project\CloudServer\restful\v0\projects.js:20:16)
    at RestfulAPIMethods.(anonymous function) (D:\able_project\CloudServer\routes\restful.js:32:60)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at module.exports (D:\able_project\CloudServer\middlewares\authRouter.js:13:10)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (D:\able_project\CloudServer\routes\restful.js:97:19)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
[2020-04-17T13:44:53.382] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T13:48:23.345] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column '_action' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'_action\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'update `project` set `_action` = \'basic\', `id` = \'P0001\', `investionSide` = \'宁波高专2\', `tutorialState` = NaN where `id` = \'P0001\'' }
[2020-04-17T13:48:43.580] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T13:48:45.936] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'tutorialState' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'tutorialState\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'update `project` set `id` = \'P0001\', `investionSide` = \'宁波高专2\', `tutorialState` = NaN where `id` = \'P0001\'' }
[2020-04-17T13:49:13.954] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-17T16:44:05.619] [ERROR] app - Request without token
[2020-04-17T16:44:05.622] [ERROR] app - 没有访问权限
[2020-04-17T16:51:38.469] [ERROR] app - 401
[2020-04-17T16:51:47.111] [ERROR] app - 403
[2020-04-17T16:51:50.574] [INFO] app - UNREISGTERED_ACCOUNT: guest
[2020-04-17T16:51:50.576] [ERROR] app - 账户不存在，可能该用户未注册
