[2020-07-28T08:30:30.508] [ERROR] app - 用户未登录
[2020-07-28T08:30:30.517] [ERROR] app - 用户未登录
[2020-07-28T08:30:30.522] [ERROR] app - 用户未登录
[2020-07-28T08:44:04.969] [ERROR] app - 用户未登录
[2020-07-28T08:44:04.978] [ERROR] app - 用户未登录
[2020-07-28T08:44:04.983] [ERROR] app - 用户未登录
[2020-07-28T08:44:50.482] [ERROR] app - 用户未登录
[2020-07-28T08:44:50.506] [ERROR] app - 用户未登录
[2020-07-28T08:44:50.513] [ERROR] app - 用户未登录
[2020-07-28T08:44:51.101] [ERROR] app - 用户未登录
[2020-07-28T08:44:51.108] [ERROR] app - 用户未登录
[2020-07-28T08:47:59.617] [ERROR] app - 用户未登录
[2020-07-28T08:48:00.175] [ERROR] app - 用户未登录
[2020-07-28T08:48:00.182] [ERROR] app - 用户未登录
[2020-07-28T08:51:20.057] [ERROR] app - 没有访问权限
[2020-07-28T08:51:20.064] [ERROR] app - 没有访问权限
[2020-07-28T09:10:33.088] [ERROR] app - 用户未登录
[2020-07-28T09:10:33.125] [ERROR] app - 用户未登录
[2020-07-28T09:10:33.142] [ERROR] app - 用户未登录
[2020-07-28T09:10:33.180] [ERROR] app - 用户未登录
[2020-07-28T09:10:33.189] [ERROR] app - 用户未登录
[2020-07-28T09:10:33.231] [ERROR] app - 用户未登录
[2020-07-28T10:41:57.110] [ERROR] app - 用户未登录
[2020-07-28T10:41:57.120] [ERROR] app - 用户未登录
[2020-07-28T10:41:57.138] [ERROR] app - 用户未登录
[2020-07-28T10:45:13.783] [ERROR] app - 用户未登录
[2020-07-28T10:45:13.790] [ERROR] app - 用户未登录
[2020-07-28T10:45:13.798] [ERROR] app - 用户未登录
[2020-07-28T10:46:48.925] [ERROR] app - TypeError: U.createId is not a function
    at Object.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\files.js:30:29)
    at RestfulAPIMethods.(anonymous function) (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:32:60)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:97:19)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-compose\index.js:42:32)
    at module.exports (C:\Users\BIM02\Desktop\ServerKT\middlewares\auth.js:75:13)
[2020-07-28T12:37:45.638] [ERROR] app - TypeError: ctx.Debug is not a function
    at Object.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\files.js:37:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-28T13:12:30.049] [ERROR] app - TypeError: ctx.Debug is not a function
    at Object.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\files.js:37:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-28T15:44:31.864] [ERROR] app - TypeError: D is not a function
    at Object.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\files.js:38:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-28T15:45:50.657] [ERROR] app - 没有访问权限
[2020-07-28T16:26:11.420] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'author' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'author\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `article` (`author`, `content`, `file_type`, `inputTime`, `inputor`, `title`, `type`, `type_id`, `updateTime`, `updator`) values (\'4123\', \'1415213\', \'TEXT\', \'2020-07-28 16:26:11\', \'sys_root\', \'法大大\', 1011, 62, \'2020-07-28 16:26:11\', \'sys_root\')' }
[2020-07-28T16:48:15.847] [ERROR] app - 没有访问权限
[2020-07-28T16:50:06.883] [ERROR] app - 没有访问权限
[2020-07-28T16:50:06.890] [ERROR] app - 没有访问权限
[2020-07-28T16:51:06.860] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'filetype' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'filetype\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `article` (`content`, `file_type`, `filetype`, `importance`, `inputTime`, `inputor`, `title`, `type_id`, `updateTime`, `updator`, `visibility`) values (\'帕金森单片机\\n阿斯加德p【\\n扫地机哦安静\\n奥时间冻结\\n少将冻结\\n少将冻结\\n扫地机偶家\\n奥时间冻结\\n阿手动脚哦偶记\\n阿扫地机偶家\\n阿手动脚哦偶记\\n扫地机偶家\\n阿手动脚哦偶记\\n扫地机偶家\\n阿善动计价\\n阿手动脚哦】\', \'TEXT\', 71, 81, \'2020-07-28 16:51:06\', \'sys_root\', \'124123\', 62, \'2020-07-28 16:51:06\', \'sys_root\', 91)' }
