[2020-12-01T01:19:38.571] [ERROR] app - API接口不存在
[2020-12-02T13:02:34.995] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:34.996] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:34.997] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:35.000] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:35.001] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:35.002] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:35.003] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:37.157] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:38.571] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.686] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.687] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.690] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.691] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.691] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.692] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:02:41.693] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:13:30.364] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:13:30.427] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:15:36.919] [ERROR] app - 非法访问
[2020-12-02T13:15:36.924] [ERROR] app - 非法访问
[2020-12-02T13:29:11.044] [ERROR] app - 用户名不存在
[2020-12-02T13:29:11.076] [ERROR] app - 用户名不存在
[2020-12-02T13:30:30.066] [ERROR] app - 用户名不存在
[2020-12-02T13:30:30.102] [ERROR] app - 用户名不存在
[2020-12-02T13:33:57.981] [ERROR] app - 用户名不存在
[2020-12-02T13:33:58.018] [ERROR] app - 用户名不存在
[2020-12-02T13:35:27.509] [ERROR] app - 用户名不存在
[2020-12-02T13:35:27.545] [ERROR] app - 用户名不存在
[2020-12-02T13:35:29.758] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.759] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.760] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.762] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.763] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.764] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:29.767] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:35:34.750] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:29.190] [ERROR] app - 用户名不存在
[2020-12-02T13:39:29.225] [ERROR] app - 用户名不存在
[2020-12-02T13:39:42.633] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.634] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.634] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.636] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.637] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.640] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:39:42.645] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:01.602] [ERROR] app - 用户名不存在
[2020-12-02T13:44:01.636] [ERROR] app - 用户名不存在
[2020-12-02T13:44:07.510] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.511] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.512] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.513] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.514] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.517] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:44:07.517] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:04.475] [ERROR] app - 用户名不存在
[2020-12-02T13:45:04.516] [ERROR] app - 用户名不存在
[2020-12-02T13:45:14.101] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.102] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.103] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.104] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.105] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.108] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:45:14.109] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.239] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.240] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.241] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.242] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.243] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.244] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:47:25.244] [ERROR] app - 不允许进行这种操作
[2020-12-02T13:48:50.572] [ERROR] app - 用户名不存在
[2020-12-02T13:48:50.611] [ERROR] app - 用户名不存在
[2020-12-02T13:58:29.123] [ERROR] app - 您无权访问该企业
[2020-12-02T13:59:04.398] [ERROR] app - 您无权访问该企业
[2020-12-02T13:59:04.432] [ERROR] app - 您无权访问该企业
[2020-12-02T13:59:18.164] [ERROR] app - ReferenceError: Enterprise is not defined
    at module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\authAccountType.js:14:34)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\response.js:8:9)
    at async cors (D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-12-02T14:00:14.399] [ERROR] app - 您无权访问该企业
[2020-12-02T14:00:14.440] [ERROR] app - 您无权访问该企业
[2020-12-02T14:00:24.673] [ERROR] app - Error: Undefined binding(s) detected when compiling FIRST query: select `id` from `enterprise` where `id` = ? and `owner_id` = ? limit ?
    at QueryCompiler_MySQL.toSQL (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\query\compiler.js:131:13)
    at Builder.toSQL (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\query\builder.js:115:44)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:56:32
    at tryCatcher (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:185:26
    at tryCatcher (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:729:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:154:17)
    at Function.Promise.using (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:169:14)
    at Runner.run (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43)
[2020-12-02T14:47:21.652] [ERROR] app - ReferenceError: entModules is not defined
    at Object.o.getAuthedModules (D:\hstigger\hstigger-server\hstigger-server\models\Module.js:198:25)
    at async Object.o.getUserInfo (D:\hstigger\hstigger-server\hstigger-server\models\Account.js:243:18)
    at async Object.o.getSessionInfo (D:\hstigger\hstigger-server\hstigger-server\models\Session.js:122:18)
    at async Object.out.Get (D:\hstigger\hstigger-server\hstigger-server\controllers\sessions.js:21:16)
    at async RestfulAPIMethods.<computed> (D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:31:26)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\authRouter.js:13:4)
    at async D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:80:7
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\authAccountType.js:40:3)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\response.js:8:9)
    at async cors (D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-12-02T14:47:22.056] [ERROR] app - ReferenceError: entModules is not defined
    at Object.o.getAuthedModules (D:\hstigger\hstigger-server\hstigger-server\models\Module.js:198:25)
    at async Object.o.getUserInfo (D:\hstigger\hstigger-server\hstigger-server\models\Account.js:243:18)
    at async Object.o.getSessionInfo (D:\hstigger\hstigger-server\hstigger-server\models\Session.js:122:18)
    at async Object.out.Get (D:\hstigger\hstigger-server\hstigger-server\controllers\sessions.js:21:16)
    at async RestfulAPIMethods.<computed> (D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:31:26)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\authRouter.js:13:4)
    at async D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:80:7
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\authAccountType.js:40:3)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\response.js:8:9)
    at async cors (D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-12-02T15:01:53.069] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.070] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.079] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.080] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.108] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.110] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.115] [ERROR] app - 您无权访问该企业
[2020-12-02T15:01:53.120] [ERROR] app - 您无权访问该企业
[2020-12-02T15:03:52.462] [ERROR] app - 您无权访问该企业
[2020-12-02T15:03:52.503] [ERROR] app - 您无权访问该企业
[2020-12-02T15:06:57.516] [ERROR] app - 您无权访问该企业
[2020-12-02T15:06:57.554] [ERROR] app - 您无权访问该企业
[2020-12-02T15:08:17.688] [ERROR] app - 您无权访问该企业
[2020-12-02T15:08:17.721] [ERROR] app - 您无权访问该企业
[2020-12-02T15:51:20.678] [ERROR] app - 您无权访问该企业
[2020-12-02T15:51:20.715] [ERROR] app - 您无权访问该企业
[2020-12-02T15:51:26.800] [ERROR] app - TypeError: File.authCOS is not a function
    at Object.o.getUserInfo (D:\hstigger\hstigger-server\hstigger-server\models\Account.js:249:23)
    at async Object.o.login (D:\hstigger\hstigger-server\hstigger-server\models\Account.js:200:18)
    at async Object.o.createSessionByLogin (D:\hstigger\hstigger-server\hstigger-server\models\Session.js:63:18)
    at async Object.out.Post (D:\hstigger\hstigger-server\hstigger-server\controllers\sessions.js:14:19)
    at async RestfulAPIMethods.<computed> (D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:31:26)
    at async D:\hstigger\hstigger-server\hstigger-server\middlewares\router.js:80:7
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\auth.js:41:7)
    at async module.exports (D:\hstigger\hstigger-server\hstigger-server\middlewares\response.js:8:9)
    at async cors (D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async D:\hstigger\hstigger-server\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-12-02T15:56:35.523] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.529] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.529] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.532] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.566] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.572] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.576] [ERROR] app - 您无权访问该企业
[2020-12-02T15:56:35.580] [ERROR] app - 您无权访问该企业
[2020-12-02T16:00:11.879] [ERROR] app - 您无权访问该企业
[2020-12-02T16:00:11.915] [ERROR] app - 您无权访问该企业
[2020-12-02T16:00:18.058] [ERROR] app - Error: ER_BAD_FIELD_ERROR: Unknown column 'vdisk' in 'field list'
    at Query.Sequence._packetToError (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'vdisk' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "insert into `file` (`created_at`, `created_by`, `ext`, `id`, `name`, `size`, `vdisk`) values ('2020-12-02 16:00:18', 'ROOT', 'xlsx', '6af20a30-3474-11eb-9118-0f27349b16d5', 'hs_user_import.xlsx', 9809, 'ref')"
}
[2020-12-02T16:00:38.225] [ERROR] app - Error: ER_BAD_FIELD_ERROR: Unknown column 'vdisk' in 'field list'
    at Query.Sequence._packetToError (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'vdisk' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "insert into `file` (`created_at`, `created_by`, `ext`, `id`, `name`, `size`, `vdisk`) values ('2020-12-02 16:00:38', 'ROOT', 'xlsx', '76faa300-3474-11eb-9118-0f27349b16d5', 'hs_user_import.xlsx', 9809, 'ref')"
}
[2020-12-02T16:01:22.395] [ERROR] app - Error: ER_NO_DEFAULT_FOR_FIELD: Field 'url' doesn't have a default value
    at Query.Sequence._packetToError (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'url' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: "insert into `file` (`created_at`, `created_by`, `ext`, `id`, `name`, `size`, `vdisk`) values ('2020-12-02 16:01:22', 'ROOT', 'xlsx', '914e4a90-3474-11eb-9341-a3168aacdd73', 'hs_user_import.xlsx', 9809, 'ref')"
}
[2020-12-02T16:01:28.262] [ERROR] app - Error: ER_NO_DEFAULT_FOR_FIELD: Field 'url' doesn't have a default value
    at Query.Sequence._packetToError (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\hstigger\hstigger-server\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (D:\hstigger\hstigger-server\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\hstigger\hstigger-server\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'url' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: "insert into `file` (`created_at`, `created_by`, `ext`, `id`, `name`, `size`, `vdisk`) values ('2020-12-02 16:01:28', 'ROOT', 'xlsx', '94cd1110-3474-11eb-9341-a3168aacdd73', 'hs_user_import.xlsx', 9809, 'ref')"
}
[2020-12-02T16:09:25.466] [ERROR] app - 您无权访问该企业
[2020-12-02T16:09:25.503] [ERROR] app - 您无权访问该企业
