[2020-04-11T08:55:17.843] [ERROR] app - 401
[2020-04-11T08:55:20.324] [ERROR] app - 401
[2020-04-11T11:03:56.209] [ERROR] app - Request without token
[2020-04-11T11:03:56.211] [ERROR] app - 没有访问权限
[2020-04-11T11:07:36.938] [ERROR] app - Request without token
[2020-04-11T11:07:36.939] [ERROR] app - 没有访问权限
[2020-04-11T15:12:25.253] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-11T15:12:33.581] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-11T15:13:16.156] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-11T15:20:13.629] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-11T15:30:01.122] [ERROR] app - { Error: ER_NO_SUCH_TABLE: Table 'gzcloud.user_group' doesn't exist
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: 'Table \'gzcloud.user_group\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
  sql: 'select * from `user_group`' }
[2020-04-11T15:30:54.185] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-11T15:36:03.273] [ERROR] app - Request without token
[2020-04-11T15:36:03.275] [ERROR] app - 没有访问权限
[2020-04-11T17:25:34.787] [ERROR] app - Request without token
[2020-04-11T17:25:34.790] [ERROR] app - 没有访问权限
